window.PRICE_CATALOG = {
  lastUpdated: "2026-09-05",
  currency: "USD",
  unit: "每 100 万 Token",
  sources: [
    {
      provider: "OpenAI",
      url: "https://developers.openai.com/api/docs/models/compare",
    },
    {
      provider: "Anthropic",
      url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    {
      provider: "Google",
      url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
  ],
  models: [
    {
      id: "gpt-6-astra",
      provider: "OpenAI",
      name: "GPT-6 Astra",
      note: "复杂推理与编码",
      input: 10,
      cachedInput: 1,
      output: 50,
    },
    {
      id: "gpt-5-6-sol",
      provider: "OpenAI",
      name: "GPT-5.6 Sol",
      note: "专业工作旗舰",
      input: 4,
      cachedInput: 0.4,
      output: 20,
    },
    {
      id: "gpt-5-6-terra",
      provider: "OpenAI",
      name: "GPT-5.6 Terra",
      note: "能力与成本均衡",
      input: 2,
      cachedInput: 0.2,
      output: 12,
    },
    {
      id: "gpt-5-6-luna",
      provider: "OpenAI",
      name: "GPT-5.6 Luna",
      note: "高吞吐、成本敏感",
      input: 0.2,
      cachedInput: 0.02,
      output: 1.2,
      highContext: {
        threshold: 272000,
        input: 0.4,
        cachedInput: 0.04,
        output: 1.8,
      },
    },
    {
      id: "claude-sonnet-5",
      provider: "Anthropic",
      name: "Claude Sonnet 5",
      note: "智能与速度均衡",
      input: 3,
      cachedInput: 0.3,
      output: 15,
    },
    {
      id: "gemini-3-5-flash-lite",
      provider: "Google",
      name: "Gemini 3.5 Flash-Lite",
      note: "轻量高频任务",
      input: 0.3,
      cachedInput: 0.03,
      output: 2.5,
    },
    {
      id: "gemini-3-1-pro-preview",
      provider: "Google",
      name: "Gemini 3.1 Pro Preview",
      note: "多模态与 Agent",
      input: 2,
      cachedInput: 0.2,
      output: 12,
      highContext: {
        threshold: 200000,
        input: 4,
        cachedInput: 0.4,
        output: 18,
      },
    },
    {
      id: "gemini-3-flash-preview",
      provider: "Google",
      name: "Gemini 3 Flash Preview",
      note: "速度优先",
      input: 0.5,
      cachedInput: 0.05,
      output: 3,
    },
  ],
};
